services:
  llama:
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan
    # rocm better, but 4GB image size
    # image: ghcr.io/ggml-org/llama.cpp:server-rocm

    container_name: llama
    # restart: always

    devices:
      - /dev/dri
      # /dev/kfd is needed for rocm, not for vulkan
      - /dev/kfd

    # needed for rocm only
    ipc: host
    # needed for rocm only
    security_opt:
      - seccomp=unconfined

    volumes:
      - llama-models-cache:/root/.cache

    ports:
    - 8080:8080

    environment:
      # needed for rocm only
      ROCBLAS_USE_HIPBLASLT: "0"

    # some model ideas that fit on strix halo 128GB
    # -hf unsloth/Qwen3-Coder-Next-GGUF:Q8_0
    # -hf unsloth/Qwen3.5-122B-A10B-GGUF:UD-Q5_K_XL
    # -hf unsloth/Qwen3.5-27B-GGUF:UD-Q8_K_XL

    # The 35B model should fit into a 16GB vram gpu
    command: >-
      -hf unsloth/Qwen3.5-35B-A3B-Q3_K_S.gguf
      --alias Qwen
      --no-mmap
      -fa on
      --host 0.0.0.0
      --port 8080
      --fit on
      --temp 0.6
      --top-p 0.95
      --top-k 20
      --min-p 0.00

  opencode:
    build: .
    # restart: always
    container_name: opencode
    volumes:
      # mount host opencode config from whereever
      - opencode.json:/home/user/.config/opencode/opencode.json:z,ro
      - opencode-session-cache:/home/user/.local/share/opencode

      # TODO: mount exactly the folder(s) you want to work on. Mind 'Z' for SELinux
      - /home/youruser/repos:/workspace:Z

    ports:
      - 4096:4096

    # start in webserver mode
    command: >-
      web
      --hostname 0.0.0.0
      --port 4096

volumes:
  llama-models-cache:
  opencode-session-cache:
